name: zipper
description: "Zip game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: 3.38.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  confetti: ^0.8.0
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^4.0.0
  flutter_riverpod: ^3.1.0
  stop_watch_timer: ^3.2.2
  flutter_colorpicker: ^1.1.0

  device_preview: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  riverpod_generator: ^4.0.0
  freezed: any

flutter:
  uses-material-design: true
